### ISSUE TITLE
 driver.findElement(By.name("Home")).click();

### ISSUE THREAD

**Issue by prashanthd** [testvagrant/AppiumDemo#2]
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html

I understood that By.name is deprecated can you provide new code for that?

And can you please provide an example for doing Parallel Android Tests?
Thanx

**Comment by imranreee** [comment]
Same here, I have tried it but `By.name` not working, could you please help us @nishantverma 

Thanks a lot for your valuable guide line

**Comment by nishantverma** [comment]
@imranreee Where exactly you get this error ? which method ?

**Comment by nishantverma** [comment]
I just ran and it works fine for me and no where "name" is used as locator.
